feedColor: Blue
inputColor: Cyan

# Supported colors: Black, GrayDark, GrayLight, White, Blue, 
# BlueLight, Cyan, CyanLight, Green, GreenLight, Magenta, MagentaLight,
# Red, RedLight, Yellow, YellowLight